### ISSUE TITLE
Should be we asking about ptf/def or "Bryce or Bob" for who pays what?

### ISSUE THREAD

**Issue by BryceStevenWilley** [mplp/docassemble-MLHMotionRegardingChildSupport#10]
On the screens themselves, we mention the names of people, but on the review screen, if someone switches the sides of the case, we then have to ask the two other questions so everything aligns. It might make more sense to just fully decouple everything, but I'm not sure.

**Comment by normon66** [comment]
Depending on how much of a nightmare if would be to decouple everything, you could just keep it simple and not give the user the option to change their party. Or, give them the opportunity to change it early on, but once they confirm that they made the correct choice, they are stuck with it.

I think Emily did something like that on the motion tool.
