### ISSUE TITLE
Selection of circuit vs. district court may not be necessary

### ISSUE THREAD

**Issue by ekressmiller** [mplp/docassemble-MLHMotionRegardingChildSupport#12]
&nbsp; | &nbsp;
-------|------------------------------------
Page title | Please choose the court where your case is.
Details | Should check with Amy, but I think it will always be circuit court, so shouldn't have to ask them.
Variable being sought | `court_index`
Package version | `0.0.1`
Filename | `docassemble.MLHMotionRegardingChildSupport:data/questions/motion_regarding_child_support.yml`

**Comment by normon66** [comment]
@ekressmiller is correct - the motion to change support (and the response) will always be in Circuit Court. 

On the 'All Tools' tab of the [MLH DIY Tool Development Google Sheet](https://docs.google.com/spreadsheets/d/1PNGnmxI_KWwGnD3Z9qHsN6REhvkF6C04BhhWKVGZyLQ/edit#gid=173384880), the `Court types` column will denote which court types a given tool needs to support.

**Comment by BryceStevenWilley** [comment]
Thanks for noting that column, I must have passed over it, and I wasn't sure if it was something that we had added in DA that wasn't in LHI yet. Just fixed that in a commit to be merged!
