### ISSUE TITLE
language suggestion

### ISSUE THREAD

**Issue by ekressmiller** [mplp/docassemble-MLHMotionRegardingChildSupport#14]
![image](https://github.com/mplp/docassemble-MLHMotionRegardingChildSupport/assets/110936328/f929c7f8-433e-4ded-931d-78412dbae504)
This page is repetitive with the previous one. Suggest combining or editing in this case to be something like:

**Need More Help?**
This tool will help you prepare forms for your legal issue without a lawyer.

If you have any questions or you aren’t sure what to do, you may want to talk to a lawyer. You can use the [Guide to Legal Help](https://michiganlegalhelp.org/guide-to-legal-help) to search for a lawyer or legal services in your area.

[I made all applicable language suggestions on the framework repo too]

**Comment by ekressmiller** [comment]
This screen also feels redundant with this one: 
![image](https://github.com/mplp/docassemble-MLHMotionRegardingChildSupport/assets/110936328/d179a02c-0edc-4056-a083-f858657638d9)

**Comment by BryceStevenWilley** [comment]
Related to #15, I think I've addressed both in an upcoming commit!
