### ISSUE TITLE
update article links once new child support articles are available

### ISSUE THREAD

**Issue by MPLP-Docassemble** [mplp/docassemble-MLHMotionRegardingChildSupport#27]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `intro screen`
Details | This tool can help you prepare the forms to file a Motion Regarding Support in Michigan.

This tool is only for parents who:
-Have a child support order in a Michigan court case and want to file a motion to change the amount of child support; OR
-Filed a Michigan divorce, custody, or child support case and want to ask the court for a temporary child support order; OR
-Have a Michigan Judgment of Divorce or a final order in a custody or paternity case that does not include child support, and want to ask the court to order child support in that case now.

To learn about changing child support without filing a motion (such as asking for a Friend of the Court support review), read Changing a Child Support Order. [link not available yet]

If you need to get a child support order, but your situation is not described above, read Getting a Child Support Order. [link not available yet]
Variable being sought | `intro_screen`
Package version | `0.0.5`
Filename | `docassemble.MLHMotionRegardingChildSupport:data/questions/motion_regarding_child_support.yml`

**Comment by BryceStevenWilley** [comment]
There is an existing article, [Getting or Changing A Child Support Order](https://michiganlegalhelp.org/resources/family/getting-or-changing-child-support-order) that I'll use until we get the specific links to each of those topics. I'll leave this issue open until we get those.

**Comment by ekressmiller** [comment]
duplicate issue
