### ISSUE TITLE
ID existing child support order: 
User feedback: language
(`has_existing_support_order`)

### ISSUE THREAD

**Issue by MPLP-Docassemble** [mplp/docassemble-MLHMotionRegardingChildSupport#34]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `existing child support order`
Details | -Change “When was the most recent judgment entered?” to “When did the judge sign the most recent Uniform Child Support Order?”

-Change “Where can I find the date on my order forms?” to “Where can I find the date on my order?” Change the answer to that question to “The date when the judge signed the order should be on the last page of the Uniform Child Support Order next to the judge’s signature.” (Please remove the two paragraphs that currently appear with the screenshot.)
I also want to change the screenshot slightly so the second yellow rectangle does not include the Certificate of Mailing. I will attempt to put the new screenshot in Github.
Variable being sought | `has_existing_support_order`
Package version | `0.0.5`
Filename | `docassemble.MLHMotionRegardingChildSupport:data/questions/motion_regarding_child_support.yml`

**Comment by ABillmire** [comment]
<img width="441" alt="UCSO pic" src="https://github.com/mplp/docassemble-MLHMotionRegardingChildSupport/assets/156249437/4e84a422-1773-4899-aa1f-faed0f3b7994">
