### ISSUE TITLE
ID current_child_support_signpost: 
User feedback: something
(`current_child_support_signpost`)

### ISSUE THREAD

**Issue by MPLP-Docassemble** [mplp/docassemble-MLHMotionRegardingChildSupport#38]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `current_child_support_signpost`
Details | We need to change the support order image in the second piece of help text. I'll upload the new image in Github.
Variable being sought | `current_child_support_signpost`
Package version | `0.0.5`
Filename | `docassemble.MLHMotionRegardingChildSupport:data/questions/motion_regarding_child_support.yml`

**Comment by ABillmire** [comment]
<img width="441" alt="UCSO table p2" src="https://github.com/mplp/docassemble-MLHMotionRegardingChildSupport/assets/156249437/22384c51-a976-4cff-a30f-b1d832c9ceaf">
