### ISSUE TITLE
ID subtotal amount: 
User feedback: something
(`subtotal_amount`)

### ISSUE THREAD

**Issue by MPLP-Docassemble** [mplp/docassemble-MLHMotionRegardingChildSupport#40]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `subtotal amount`
Details | The screenshot in the help text needs to be updated. I will upload the new image to Github.
Variable being sought | `subtotal_amount`
Package version | `0.0.5`
Filename | `docassemble.MLHMotionRegardingChildSupport:data/questions/motion_regarding_child_support.yml`

**Comment by ABillmire** [comment]
<img width="576" alt="UCSO subtotal" src="https://github.com/mplp/docassemble-MLHMotionRegardingChildSupport/assets/156249437/87617fc4-30f5-4784-951d-b97be0b35ec5">
