### ISSUE TITLE
ID child support formula FYI: 
User feedback: language
(`support_formula_fyi`)

### ISSUE THREAD

**Issue by MPLP-Docassemble** [mplp/docassemble-MLHMotionRegardingChildSupport#41]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `child support formula FYI`
Details | Change language to:

If you have not done so already, use the MiChildSupport Calculator now to calculate child support based on the Michigan Child Support Formula. [entire preceding sentence in bold] [link to Calculator: https://micase.state.mi.us/calculatorapp/public/welcome/load.html] You will see the child support numbers at the end of the calculation on the results page.

If you are asking for the Support Formula amounts in your motion, you will need the Calculator results page to answer the questions in this tool. If you are asking for different amounts, you will still need the Calculator results page to complete the Uniform Child Support Order Deviation Addendum that you will download at the end of this tool.

[New help text question:] Why do I need to calculate child support using the MIChildSupport Calculator?

[Answer:]
The court must order child support according to the Michigan Child Support Formula, unless the court finds the result would be unfair or inappropriate. This is true even if the parties agree to an amount that differs from the Support Formula amount.
Variable being sought | `support_formula_fyi`
Package version | `0.0.5`
Filename | `docassemble.MLHMotionRegardingChildSupport:data/questions/motion_regarding_child_support.yml`

**Comment by ABillmire** [comment]
Just to clarify, this new language should replace the old language for both a request to change support and a request to establish support.

**Comment by BryceStevenWilley** [comment]
That page is used for both flows, so the change should work for the request to establish as well.
