### ISSUE TITLE
Is "paid_support_costs" always true?

### ISSUE THREAD

**Issue by BryceStevenWilley** [mplp/docassemble-MLHMotionRegardingChildSupport#5]
It seems to be always checked, but want to make sure. Check LHI or ask around.

**Comment by normon66** [comment]
In the DA template, `paid_support_costs` is D(2), seen below.
   ![image](https://github.com/mplp/docassemble-MLHMotionRegardingChildSupport/assets/32527754/53d93dfb-ac53-4494-a91e-fe3c54080cbd)

In HotDocs, this is `P1 CO`, which calls `Prior order Y CO`, which inserts an X if `Prior order CO` is true, which is just the value of `Prior order TF`, which is set when Yes is clicked in the below page of the A2J interview:

   ![image](https://github.com/mplp/docassemble-MLHMotionRegardingChildSupport/assets/32527754/35f960e6-a876-4735-b98f-24559b616d5b)

<good lord... could've just used the TF variable!>
