### ISSUE TITLE
Do we need to handle International addresses?

### ISSUE THREAD

**Issue by BryceStevenWilley** [mplp/docassemble-MLHMotionRegardingChildSupport#6]
LHI has a separate screen for it. If we do, it'll need to be added upstream in AL.

**Comment by BryceStevenWilley** [comment]
Assembly Line [does not yet have a way](https://github.com/SuffolkLITLab/docassemble-AssemblyLine/blob/a3c4723b69b6a87e0516b6f79afefea3c5a1ac55/docassemble/AssemblyLine/al_general.py#L1138) to ask for international addresses.

Some other approaches:

* USWDS suggests [something from the Universal Postal Union](https://www.upu.int/en/Postal-Solutions/Programmes-Services/Addressing-Solutions) for international addresses, though I'm not sure how to use it
* https://www.uxmatters.com/mt/archives/2008/06/international-address-fields-in-web-forms.php is a good resource. It suggests splitting things up into the same structure as we currently have for US, just using more generic labels, like Address Line 1, Address Line 2, City, State/Province/Region, and Zip/Postal Code.  https://web.dev/learn/forms/internationalization/#allow_a_variety_of_address_formats also links back to there, so it seems to be the most passed around resource for this stuff.

Most of the other sources that I see just support two countries (US and CA, or AU and NZ). I can look up some other suggested ways of asking those questions.

**Comment by normon66** [comment]
You may have already seen this in the HotDocs component file, but here's how that's handled behind-the-scenes. 

![image](https://github.com/mplp/docassemble-MLHMotionRegardingChildSupport/assets/32527754/695cab6b-ec49-47aa-862d-0b0ac2f58677)

And of course in A2J, when address is not in US:
![image](https://github.com/mplp/docassemble-MLHMotionRegardingChildSupport/assets/32527754/2d3840f7-1f62-4644-a537-ad4248eb0631)

![image](https://github.com/mplp/docassemble-MLHMotionRegardingChildSupport/assets/32527754/87cd0b97-0c9c-4dab-ba47-de4bc1e725fd)

**Comment by BryceStevenWilley** [comment]
Missed the upstream issue for this for some reason; https://github.com/SuffolkLITLab/docassemble-AssemblyLine/issues/281

**Comment by BryceStevenWilley** [comment]
Did some more work upstream in the linked issue; in short, we can use something very similar to the US only address input. The only difference is that the state field will be a text input, not a drop down select. More details in the above issue, but it just doesn't work well with Google autocomplete, which I'd put at a higher priority than us getting the exact province / state name spelled correctly.
