### ISSUE TITLE
wording on who pays question

### ISSUE THREAD

**Issue by ekressmiller** [mplp/docassemble-MLHMotionRegardingChildSupport#60]
note question "who are you asking the court to pay support" feels a little confusing. Feels like you could be asking who the court is going to pay support _to_

Question is either:

  In your agreement with ${ OP }, who are you asking the court to pay support?

or:

  Who are you asking the court to pay support?

**Comment by ekressmiller** [comment]
I guess it kind of makes sense, but it's confusing.

what about:  Who do you want the court to order to pay support?

**Comment by ekressmiller** [comment]
Who should pay support?

Who should be ordered to pay support?

**Comment by ABillmire** [comment]
I agree. Let's go with "Who should be ordered to pay support?"
