### ISSUE TITLE
Do we need hearing info?

### ISSUE THREAD

**Issue by BryceStevenWilley** [mplp/docassemble-MLHMotionRegardingChildSupport#7]
There are spots on the form for hearing information, just like in [simpmotion](https://github.com/mplp/docassemble-Simpmotion), but the LHI interview doesn't have it.

**Comment by normon66** [comment]
In the LHI/HotDocs form, the hearing information on FOC 50 is blank. No need to collect this.

**Comment by BryceStevenWilley** [comment]
Sounds good! I'll close this issue; if it's something we want to add post-MVP we can re-open. I'm not sure how useful it'd be though.
